apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-controller
  namespace: ingress-nginx
  labels:
    k8s-app: nginx-ingress-controller
  annotations:
#    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
#    service.beta.kubernetes.io/oci-load-balancer-ssl-ports: 443
    service.beta.kubernetes.io/oci-load-balancer-shape: 100Mbps
#    service.beta.kubernetes.io/oci-load-balancer-tls-secret: tls-secret
spec:
  type: LoadBalancer
#  loadBalancerSourceRanges:
#  - 216.253.231.194/32
#  - 128.136.211.68/32
  ports:
  - port: 80
    name: http
    protocol: TCP
    targetPort: 80
  selector:
    k8s-app: nginx-ingress-controller
